name: Validate Home Assistant integration

on:
  push:
  pull_request:

jobs:
  hassfest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Validate Home Assistant integration
        uses: home-assistant/actions/hassfest@main
        with:
          path: .
