"""Constants for Solar Web Public."""

from __future__ import annotations

DOMAIN = "solar_web_public"

CONF_NAME = "name"
CONF_SHARED_URL = "shared_url"
CONF_REFRESH_INTERVAL = "refresh_interval"
CONF_ENABLED_SENSORS = "enabled_sensors"
CONF_ENABLED_SENSOR_GROUPS = "enabled_sensor_groups"

DEFAULT_REFRESH_INTERVAL = 300

PLATFORMS = ["sensor"]

SENSOR_PLANT = "plant"
SENSOR_CURRENT_POWER = "current_power"
SENSOR_PRODUCTION_POWER = "production_power"
SENSOR_CONSUMPTION_POWER = "consumption_power"
SENSOR_GRID_POWER = "grid_power"
SENSOR_FEED_IN_POWER = "feed_in_power"
SENSOR_GRID_IMPORT_POWER = "grid_import_power"
SENSOR_BATTERY_POWER = "battery_power"
SENSOR_BATTERY_SOC = "battery_soc"
SENSOR_TODAY_ENERGY = "today_energy"
SENSOR_MONTH_ENERGY = "month_energy"
SENSOR_YEAR_ENERGY = "year_energy"
SENSOR_TOTAL_ENERGY = "total_energy"
SENSOR_GRID_EXPORT_ENERGY_TODAY = "grid_export_energy_today"
SENSOR_GRID_IMPORT_ENERGY_TODAY = "grid_import_energy_today"
SENSOR_TODAY_EARNING = "today_earning"
SENSOR_MONTH_EARNING = "month_earning"
SENSOR_YEAR_EARNING = "year_earning"
SENSOR_TOTAL_EARNING = "total_earning"
SENSOR_DIAGNOSTICS = "diagnostics"

SENSOR_GROUP_POWER = "power"
SENSOR_GROUP_ENERGY = "energy"
SENSOR_GROUP_GRID = "grid"
SENSOR_GROUP_BATTERY = "battery"
SENSOR_GROUP_EARNINGS = "earnings"
SENSOR_GROUP_DIAGNOSTICS = "diagnostics"

SENSOR_GROUP_LABELS = {
    SENSOR_GROUP_POWER: "Potenze",
    SENSOR_GROUP_ENERGY: "Energie",
    SENSOR_GROUP_GRID: "Rete",
    SENSOR_GROUP_BATTERY: "Batteria",
    SENSOR_GROUP_EARNINGS: "Guadagni",
    SENSOR_GROUP_DIAGNOSTICS: "Diagnostica",
}

SENSOR_GROUPS = {
    SENSOR_GROUP_POWER: [
        SENSOR_CURRENT_POWER,
        SENSOR_PRODUCTION_POWER,
        SENSOR_CONSUMPTION_POWER,
    ],
    SENSOR_GROUP_GRID: [
        SENSOR_GRID_POWER,
        SENSOR_FEED_IN_POWER,
        SENSOR_GRID_IMPORT_POWER,
        SENSOR_GRID_EXPORT_ENERGY_TODAY,
        SENSOR_GRID_IMPORT_ENERGY_TODAY,
    ],
    SENSOR_GROUP_BATTERY: [
        SENSOR_BATTERY_POWER,
        SENSOR_BATTERY_SOC,
    ],
    SENSOR_GROUP_ENERGY: [
        SENSOR_TODAY_ENERGY,
        SENSOR_MONTH_ENERGY,
        SENSOR_YEAR_ENERGY,
        SENSOR_TOTAL_ENERGY,
    ],
    SENSOR_GROUP_EARNINGS: [
        SENSOR_TODAY_EARNING,
        SENSOR_MONTH_EARNING,
        SENSOR_YEAR_EARNING,
        SENSOR_TOTAL_EARNING,
    ],
    SENSOR_GROUP_DIAGNOSTICS: [
        SENSOR_PLANT,
        SENSOR_DIAGNOSTICS,
    ],
}

ALL_SENSOR_KEYS = [
    SENSOR_PLANT,
    SENSOR_CURRENT_POWER,
    SENSOR_PRODUCTION_POWER,
    SENSOR_CONSUMPTION_POWER,
    SENSOR_GRID_POWER,
    SENSOR_FEED_IN_POWER,
    SENSOR_GRID_IMPORT_POWER,
    SENSOR_BATTERY_POWER,
    SENSOR_BATTERY_SOC,
    SENSOR_TODAY_ENERGY,
    SENSOR_MONTH_ENERGY,
    SENSOR_YEAR_ENERGY,
    SENSOR_TOTAL_ENERGY,
    SENSOR_GRID_EXPORT_ENERGY_TODAY,
    SENSOR_GRID_IMPORT_ENERGY_TODAY,
    SENSOR_TODAY_EARNING,
    SENSOR_MONTH_EARNING,
    SENSOR_YEAR_EARNING,
    SENSOR_TOTAL_EARNING,
    SENSOR_DIAGNOSTICS,
]

DEFAULT_ENABLED_SENSOR_KEYS = [
    SENSOR_PLANT,
    SENSOR_CURRENT_POWER,
    SENSOR_CONSUMPTION_POWER,
    SENSOR_GRID_POWER,
    SENSOR_FEED_IN_POWER,
    SENSOR_BATTERY_SOC,
    SENSOR_TODAY_ENERGY,
    SENSOR_TOTAL_ENERGY,
    SENSOR_GRID_EXPORT_ENERGY_TODAY,
    SENSOR_GRID_IMPORT_ENERGY_TODAY,
    SENSOR_DIAGNOSTICS,
]

SENSOR_LABELS = {
    SENSOR_PLANT: "Stato impianto",
    SENSOR_CURRENT_POWER: "Potenza attuale",
    SENSOR_PRODUCTION_POWER: "Potenza produzione",
    SENSOR_CONSUMPTION_POWER: "Potenza consumo",
    SENSOR_GRID_POWER: "Potenza rete",
    SENSOR_FEED_IN_POWER: "Potenza immessa in rete",
    SENSOR_GRID_IMPORT_POWER: "Potenza prelevata dalla rete",
    SENSOR_BATTERY_POWER: "Potenza batteria",
    SENSOR_BATTERY_SOC: "Batteria",
    SENSOR_TODAY_ENERGY: "Energia oggi",
    SENSOR_MONTH_ENERGY: "Energia mese",
    SENSOR_YEAR_ENERGY: "Energia anno",
    SENSOR_TOTAL_ENERGY: "Energia totale",
    SENSOR_GRID_EXPORT_ENERGY_TODAY: "Energia immessa oggi",
    SENSOR_GRID_IMPORT_ENERGY_TODAY: "Energia prelevata oggi",
    SENSOR_TODAY_EARNING: "Guadagno oggi",
    SENSOR_MONTH_EARNING: "Guadagno mese",
    SENSOR_YEAR_EARNING: "Guadagno anno",
    SENSOR_TOTAL_EARNING: "Guadagno totale",
    SENSOR_DIAGNOSTICS: "Diagnostica",
}